### ISSUE TITLE
Can't paste custom snippet

### ISSUE THREAD

**Issue by Classiks** [JeroenVerstraelen/CopilotWithContext#1]
Hey,

love the idea of the extension. However, whenever I'm saving a custom snippet and then want to paste it. Nothing happens. Not when I click on the snippet, write it out, press enter or anything else. Could it have sth to do with the Vim Extension?

Thank you for your work and best,

Daniel

**Comment by JeroenVerstraelen** [comment]
Hey, 

thanks for using the extension! I made some major changes just a moment ago to simplify the extension and fix some bugs. Could you update to the latest version (0.1.0) and try again?

This is what it looks like right now when I add a snippet and paste it:
![](https://i.imgur.com/X8LdtEy.gif)

**Comment by Classiks** [comment]
Works like a charm! Thank you!
